## Non Graded Challenge 5

In [1]:
#import lib
import numpy as np

1. Membuat Tensor

In [6]:
tensor = np.array([
    [[23,50],[7,12]],
    [[57,67],[99,43]],
    [[75,21],[57,12]],
    [[87,26],[18,84]]
])

print(tensor)
print(tensor.shape)

[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]
(4, 2, 2)


2. Melakukan perkalian terhadap matriks A dan B

In [13]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
B = np.array([17,22,19])
print('matriks A adalah',A)
print('\nmatriks B adalah', B)

print(B)
#Perkalian dengan matriks A
print('\nHasil perkalian matriks A dengan matriks B adalah', A@B)

matriks A adalah [[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]

matriks B adalah [17 22 19]
[17 22 19]

Hasil perkalian matriks A dengan matriks B adalah [1852 2454 4305]


3. Melakukan transpose, hitung determinan, dan inverse matriks A

In [20]:
#Transpose
print('transpose matriks A adalah\n',A.transpose())

#determinan
print('\ndeterminan matriks A adalah', np.linalg.det(A))

#inverse matriks
print('\ninverse matriks A adalah\n',np.linalg.inv(A))

transpose matriks A adalah
 [[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]

determinan matriks A adalah 131344.0000000002

inverse matriks A adalah
 [[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
